name: ragmac_xdem
channels:
  - conda-forge
  - oggm
dependencies:
  - numpy
  - scipy
  - matplotlib
  - toml
  - pandas
  - xdem
  - opencv
  - oggm
  - oggm-deps
  - pip
  # dev requirements
  - pytest
  - pip:
    - -e "git+https://github.com/GlacioHack/GeoUtils.git@main#egg=geoutils"
    - -e "git+https://github.com/GlacioHack/xdem.git@main#egg=xdem"
